/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import dataBase.MySQLConnection;
import entity.User;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;

/**
 *
 * @author Pablo
 */
public class LogInFrame extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form LogInFrame
     */
    public LogInFrame(MainFrameApp mainFrame) {
        initComponents();
        setLocationRelativeTo(null);
        loggedUser = false;
        register = new RegisterFrame(this);
        this.mainFrame = mainFrame;
        this.connection = mainFrame.getConnection();
        signInButton.addActionListener(this);
        exitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        registerButton.addActionListener(register);

    }

    private void loadUser(int id) {

        user = new User(connection);
        String query = "select pk_id_usuario,nombre,apellido,email,telefono,progreso"
                + "alumno_111mil from usuario where pk_id_usuario=" + id;
        connection.executeQuery(query);
        ResultSet res = connection.getResultSet();
        try {
            user.setIdUser(res.getInt("pk_id_usuario"));
            user.setName(res.getString("nombre"));
            user.setSurname(res.getString("apellido"));
            user.seteMail(res.getString("email"));
            user.setTelephoneNumber(res.getString("telefono"));
            user.setProgress(res.getInt("progreso"));
            user.setIs111Student(res.getBoolean("alumno_111mil"));
        } catch (SQLException ex) {
            ex.printStackTrace();//ver si hay que hacer caso al warning del IDE (si optamos por
            //imprimir por consola el objeto, el warning desaparece).
            //en varias partes del codigo invoque a printStackTrace (ver si hay que modificar todo eso).
        }

    }

    public User getUser() {

        return user;

    }

    public boolean getLoggedUser() {

        return loggedUser;

    }

    public MySQLConnection getConnection() {

        return this.connection;

    }

    private boolean validateLogIn() throws SQLException {

        String userField = userTextField.getText();
        char[] passwordField = userPasswordField.getPassword();
        String password = null;
        for (Character c : passwordField) {

            password += c;

        }
        if ((connection.checkExistingValue(userField, "email", "usuario") && (connection.checkExistingValue(password, "contraseña", "usuario")))) {

            String query = "select pk_id_usuario from usuario where email=" + userField + " and contraseña=" + password;
            ResultSet res = connection.getResultSet();
            loadUser(res.getInt("pk_id_usuario"));
            return true;

        } else {

            return false;

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userTextField = new javax.swing.JTextField();
        userPasswordField = new javax.swing.JPasswordField();
        signInButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        exitButton.setText("Salir");

        userLabel.setText("Usuario (e-mail):");

        passwordLabel.setText("Contraseña:");

        userPasswordField.setText("jPasswordField1");

        signInButton.setText("Iniciar Sesion");

        registerButton.setText("Registrarse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordLabel)
                            .addComponent(userLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(userTextField))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitButton)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signInButton))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton)
                .addGap(236, 236, 236)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(userPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(signInButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private MainFrameApp mainFrame;
    private User user;//este objeto lo instancio aca. Lo seteo en la instancia de main frame.
    private MySQLConnection connection;
    private RegisterFrame register;
    private boolean loggedUser;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton signInButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JPasswordField userPasswordField;
    private javax.swing.JTextField userTextField;
    // End of variables declaration//GEN-END:variables

    public JButton getSingInButton() {

        return signInButton;

    }
    
    public JButton getRegisterButton(){
    
        return registerButton;
        
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        JButton b = (JButton) e.getSource();
        if (b == signInButton) {
            try {
                if (validateLogIn()) {
                    loggedUser = true;
                    this.setVisible(false);
                    mainFrame.setVisible(true);

                }
            } catch (SQLException ex) {
                ex.printStackTrace();//me generaba otro codigo pero lo simplifique llamando al stacktrace del objeto (no se si esta bien).
            }
        }else if(b==mainFrame.getNorthPanel().getCloseSessionButton()){
        //NOTA: ver si hay que hacer/modificar algo mas en el proceso de cerrar la sesion.
            mainFrame.dispose();//no estoy seguro de ese dispose()
            this.setVisible(true);
            
        }
    }
}
